### ISSUE TITLE
Problem for linking the example 6: "undefined reference to `omp_get_num_threads'"

### ISSUE THREAD

**Issue by lannnnn** [Alisah-Ozcan/HEonGPU#2]
Hi, I'm trying to use your GPU FHE lib, while I meet some problem on compiling the examples. I set `DHEonGPU_BUILD_EXAMPLES=ON ` and have passed all the other steps. But when it reach the step to link the lib for exp6(only this exp use openmp and it occurs the error) I get the error:

```
tmpxft_003e9f9a_00000000-7_6_multi_stream_usage_way1.cudafe1.cpp:(.text+0x9c5): undefined reference to 'omp_get_num_threads'
/usr/bin/ld: tmpxft_003e9f9a_00000000-7_6_multi_stream_usage_way1.cudafe1.cpp:(.text+0x9cd): undefined reference to 'omp_get_thread_num'
```

I didn't modified the CMakeFIle while I don't understand what happens since all the things seems should work but not. Can you help to figure out what's the problem?

**Comment by Alisah-Ozcan** [comment]
I will check it and let you know.

**Comment by Alisah-Ozcan** [comment]
I've made an edit now, if the problem still persists, can you share with me the nvcc, gcc, cmake and openmp versions you are using?
Just put this to your terminal.
-  nvcc --version
-  gcc --version
- cmake --version

For checking openMP version, use them one by one;
- echo '#include <omp.h>
#include <stdio.h>
int main() {
    printf("OpenMP version: %d\\n", _OPENMP);
    return 0;
}' > check_openmp.c
- gcc -fopenmp check_openmp.c -o check_openmp
- ./check_openmp

**Comment by lannnnn** [comment]
Thx, it now works for me :)
